#\uD504\uB85C\uD37C\uD2F0 \uAE30\uB85D_2024-10-16
#Wed Oct 16 16:09:04 KST 2024
appender.console.filter.threshold.level=debug
appender.console.filter.threshold.type=ThresholdFilter
appender.console.layout.pattern=[%d{yyyy-MM-dd HH\:mm}] %M(%F\:%L) \: %m%n
appender.console.layout.type=PatternLayout
appender.console.name=STDOUT
appender.console.type=Console
appender.rolling.fileName=${filename}.log
appender.rolling.filePattern=${filename}.%d{yyyy-MM-dd}.log
appender.rolling.filter.threshold.level=debug
appender.rolling.filter.threshold.type=ThresholdFilter
appender.rolling.layout.pattern=[%d{yyyy-MM-dd HH\:mm\:ss}] %-5p %C{1}.%M(%F\:%L) - %m%n
appender.rolling.layout.type=PatternLayout
appender.rolling.name=RollingFile
appender.rolling.policies.time.interval=1
appender.rolling.policies.time.modulate=true
appender.rolling.policies.time.type=TimeBasedTriggeringPolicy
appender.rolling.policies.type=Policies
appender.rolling.strategy.max=3
appender.rolling.strategy.type=DefaultRolloverStrategy
appender.rolling.type=RollingFile
name=PCWK_PropertiesConfig
name_han=\uD55C\uAE00
property.filename=pcwk_log4j2.log
rootLogger.appenderRef.rolling.ref=RollingFile
rootLogger.appenderRef.stdout.ref=STDOUT
rootLogger.appenderRefs=rolling, STDOUT
rootLogger.level=debug
